import { Sequence } from "./components/SequenceViz";
export const chain2_sequence: Sequence = {
  residues: [
    { resi: 0, resn: "M", chain: "B" },
    { resi: 1, resn: "R", chain: "B" },
    { resi: 2, resn: "G", chain: "B" },
    { resi: 3, resn: "A", chain: "B" },
    { resi: 4, resn: "L", chain: "B" },
    { resi: 5, resn: "L", chain: "B" },
    { resi: 6, resn: "V", chain: "B" },
    { resi: 7, resn: "L", chain: "B" },
    { resi: 8, resn: "A", chain: "B" },
    { resi: 9, resn: "L", chain: "B" },
    { resi: 10, resn: "L", chain: "B" },
    { resi: 11, resn: "V", chain: "B" },
    { resi: 12, resn: "T", chain: "B" },
    { resi: 13, resn: "Q", chain: "B" },
    { resi: 14, resn: "A", chain: "B" },
    { resi: 15, resn: "L", chain: "B" },
    { resi: 16, resn: "G", chain: "B" },
    { resi: 17, resn: "V", chain: "B" },
    { resi: 18, resn: "K", chain: "B" },
    { resi: 19, resn: "M", chain: "B" },
    { resi: 20, resn: "A", chain: "B" },
    { resi: 21, resn: "E", chain: "B" },
    { resi: 22, resn: "T", chain: "B" },
    { resi: 23, resn: "C", chain: "B" },
    { resi: 24, resn: "P", chain: "B" },
    { resi: 25, resn: "I", chain: "B" },
    { resi: 26, resn: "F", chain: "B" },
    { resi: 27, resn: "Y", chain: "B" },
    { resi: 28, resn: "D", chain: "B" },
    { resi: 29, resn: "V", chain: "B" },
    { resi: 30, resn: "F", chain: "B" },
    { resi: 31, resn: "F", chain: "B" },
    { resi: 32, resn: "A", chain: "B" },
    { resi: 33, resn: "V", chain: "B" },
    { resi: 34, resn: "A", chain: "B" },
    { resi: 35, resn: "N", chain: "B" },
    { resi: 36, resn: "G", chain: "B" },
    { resi: 37, resn: "N", chain: "B" },
    { resi: 38, resn: "E", chain: "B" },
    { resi: 39, resn: "L", chain: "B" },
    { resi: 40, resn: "L", chain: "B" },
    { resi: 41, resn: "L", chain: "B" },
    { resi: 42, resn: "D", chain: "B" },
    { resi: 43, resn: "L", chain: "B" },
    { resi: 44, resn: "S", chain: "B" },
    { resi: 45, resn: "L", chain: "B" },
    { resi: 46, resn: "T", chain: "B" },
    { resi: 47, resn: "K", chain: "B" },
    { resi: 48, resn: "V", chain: "B" },
    { resi: 49, resn: "N", chain: "B" },
    { resi: 50, resn: "A", chain: "B" },
    { resi: 51, resn: "T", chain: "B" },
    { resi: 52, resn: "E", chain: "B" },
    { resi: 53, resn: "P", chain: "B" },
    { resi: 54, resn: "E", chain: "B" },
    { resi: 55, resn: "R", chain: "B" },
    { resi: 56, resn: "T", chain: "B" },
    { resi: 57, resn: "A", chain: "B" },
    { resi: 58, resn: "M", chain: "B" },
    { resi: 59, resn: "K", chain: "B" },
    { resi: 60, resn: "K", chain: "B" },
    { resi: 61, resn: "I", chain: "B" },
    { resi: 62, resn: "Q", chain: "B" },
    { resi: 63, resn: "D", chain: "B" },
    { resi: 64, resn: "C", chain: "B" },
    { resi: 65, resn: "Y", chain: "B" },
    { resi: 66, resn: "V", chain: "B" },
    { resi: 67, resn: "E", chain: "B" },
    { resi: 68, resn: "N", chain: "B" },
    { resi: 69, resn: "G", chain: "B" },
    { resi: 70, resn: "L", chain: "B" },
    { resi: 71, resn: "I", chain: "B" },
    { resi: 72, resn: "S", chain: "B" },
    { resi: 73, resn: "R", chain: "B" },
    { resi: 74, resn: "V", chain: "B" },
    { resi: 75, resn: "L", chain: "B" },
    { resi: 76, resn: "D", chain: "B" },
    { resi: 77, resn: "G", chain: "B" },
    { resi: 78, resn: "L", chain: "B" },
    { resi: 79, resn: "V", chain: "B" },
    { resi: 80, resn: "M", chain: "B" },
    { resi: 81, resn: "T", chain: "B" },
    { resi: 82, resn: "T", chain: "B" },
    { resi: 83, resn: "I", chain: "B" },
    { resi: 84, resn: "S", chain: "B" },
    { resi: 85, resn: "S", chain: "B" },
    { resi: 86, resn: "S", chain: "B" },
    { resi: 87, resn: "K", chain: "B" },
    { resi: 88, resn: "D", chain: "B" },
    { resi: 89, resn: "C", chain: "B" },
    { resi: 90, resn: "M", chain: "B" },
    { resi: 91, resn: "G", chain: "B" },
    { resi: 92, resn: "E", chain: "B" },
    { resi: 93, resn: "A", chain: "B" },
    { resi: 94, resn: "V", chain: "B" },
    { resi: 95, resn: "Q", chain: "B" },
    { resi: 96, resn: "N", chain: "B" },
    { resi: 97, resn: "T", chain: "B" },
    { resi: 98, resn: "V", chain: "B" },
    { resi: 99, resn: "E", chain: "B" },
    { resi: 100, resn: "D", chain: "B" },
    { resi: 101, resn: "L", chain: "B" },
    { resi: 102, resn: "K", chain: "B" },
    { resi: 103, resn: "L", chain: "B" },
    { resi: 104, resn: "N", chain: "B" },
    { resi: 105, resn: "T", chain: "B" },
    { resi: 106, resn: "L", chain: "B" },
    { resi: 107, resn: "G", chain: "B" },
    { resi: 108, resn: "R", chain: "B" },
  ],
  variants: [
    {
      id: 0,
      indices: [14],
      stats: [
        "SNP: A/E",
        "44.0% of cats (50 total)",
        "13 cats with ambiguity A/E",
        "9 cats with substitution E",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 1,
      indices: [28],
      stats: [
        "SNP: D/E",
        "12.0% of cats (50 total)",
        "6 cats with ambiguity D/E",
      ],
      variant_type: "domestic",
      correlated_ids: [2, 3],
    },
    {
      id: 2,
      indices: [31],
      stats: [
        "MNP: F/T/S/I",
        "34.0% of cats (50 total)",
        "8 cats with substitution T",
        "8 cats with  F/T/S/I",
        "1 cats with rare mutation T/S",
      ],
      variant_type: "domestic",
      correlated_ids: [3],
    },
    {
      id: 3,
      indices: [35],
      stats: [
        "SNP: N/S",
        "34.0% of cats (50 total)",
        "8 cats with substitution S",
        "9 cats with ambiguity N/S",
      ],
      variant_type: "domestic",
      correlated_ids: [2],
    },
    {
      id: 4,
      indices: [37],
      stats: [
        "SNP: N/D",
        "14.0% of cats (50 total)",
        "4 cats with ambiguity N/D",
        "3 cats with substitution D",
      ],
      variant_type: "domestic",
      correlated_ids: [2, 3],
    },
    {
      id: 5,
      indices: [43],
      stats: [
        "SNP: L/F/S",
        "20.0% of cats (50 total)",
        "10 cats with ambiguity L/F/S",
      ],
      variant_type: "domestic",
      correlated_ids: [9],
    },
    {
      id: 6,
      indices: [71],
      stats: [
        "SNP: I/L/V",
        "86.0% of cats (50 total)",
        "12 cats with ambiguity I/V",
        "8 cats with substitution V",
        "8 cats with ambiguity I/L",
        "13 cats with ambiguity V/L",
        "2 cats with substitution L",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 7,
      indices: [73],
      stats: [
        "SNP: R/K",
        "66.0% of cats (50 total)",
        "25 cats with ambiguity R/K",
        "8 cats with substitution K",
      ],
      variant_type: "domestic",
      correlated_ids: [8],
    },
    {
      id: 8,
      indices: [74],
      stats: [
        "SNP: V/F/A/S",
        "66.0% of cats (50 total)",
        "11 cats with ambiguity V/F",
        "4 cats with ambiguity V/F/A/S",
        "14 cats with ambiguity V/A",
        "4 cats with substitution F",
      ],
      variant_type: "domestic",
      correlated_ids: [7],
    },
    {
      id: 9,
      indices: [77],
      stats: [
        "SNP: G/A/T/R",
        "36.0% of cats (50 total)",
        "16 cats with ambiguity G/A/T/R",
        "2 cats with ambiguity G/A",
      ],
      variant_type: "domestic",
      correlated_ids: [7, 8],
    },
    {
      id: 10,
      indices: [81],
      stats: [
        "SNP: T/I",
        "64.0% of cats (50 total)",
        "23 cats with substitution I",
        "9 cats with ambiguity T/I",
      ],
      variant_type: "domestic",
      correlated_ids: [11, 12, 13, 14, 15, 16, 17],
    },
    {
      id: 11,
      indices: [82],
      stats: [
        "SNP: T/A",
        "42.0% of cats (50 total)",
        "18 cats with substitution A",
        "3 cats with ambiguity T/A",
      ],
      variant_type: "domestic",
      correlated_ids: [10, 12, 13, 14, 15, 16, 17],
    },
    {
      id: 12,
      indices: [83],
      stats: ["SNP: I/-", "42.0% of cats (50 total)", "21 cats with abscence"],
      variant_type: "domestic",
      correlated_ids: [10, 11, 13, 14, 15, 16, 17],
    },
    {
      id: 13,
      indices: [84],
      stats: [
        "SNP: S/-",
        "42.0% of cats (50 total)",
        "21 cats with substitution -",
      ],
      variant_type: "domestic",
      correlated_ids: [10, 11, 12, 14, 15, 16, 17],
    },
    {
      id: 14,
      indices: [85],
      stats: [
        "SNP: S/-",
        "42.0% of cats (50 total)",
        "21 cats with substitution -",
      ],
      variant_type: "domestic",
      correlated_ids: [10, 11, 12, 13, 15, 16, 17],
    },
    {
      id: 15,
      indices: [86],
      stats: [
        "SNP: S/N",
        "42.0% of cats (50 total)",
        "21 cats with substitution N",
      ],
      variant_type: "domestic",
      correlated_ids: [10, 11, 12, 13, 14, 16, 17],
    },
    {
      id: 16,
      indices: [87],
      stats: [
        "SNP: V",
        "40.0% of cats (50 total)",
        "13 cats with substitution V",
        "5 cats with substitution E",
        "2 cats with ambiguity E/V",
      ],
      variant_type: "domestic",
      correlated_ids: [10, 11, 12, 13, 14, 15, 17],
    },
    {
      id: 17,
      indices: [88],
      stats: [
        "SNP: Y",
        "14.0% of cats (50 total)",
        "2 cats with ambiguity D/Y",
        "5 cats with substitution Y",
      ],
      variant_type: "domestic",
      correlated_ids: [10, 11, 12, 13, 14, 15, 16],
    },
    {
      id: 18,
      indices: [90],
      stats: [
        "SNP: M/T",
        "30.0% of cats (50 total)",
        "9 cats with ambiguity M/T",
        "6 cats with substitution T",
      ],
      variant_type: "domestic",
      correlated_ids: [0],
    },
    {
      id: 19,
      indices: [95],
      stats: [
        "SNP: Q/E",
        "34.0% of cats (50 total)",
        "4 cats with ambiguity Q/E",
        "13 cats with substitution E",
      ],
      variant_type: "domestic",
      correlated_ids: [20],
    },
    {
      id: 20,
      indices: [104],
      stats: [
        "SNP: N/K",
        "34.0% of cats (50 total)",
        "4 cats with ambiguity N/K",
        "13 cats with substitution K",
      ],
      variant_type: "domestic",
      correlated_ids: [19],
    },
    {
      correlated_ids: [],
      id: 21,
      indices: [8],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution T"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 22,
      indices: [13],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution R"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 23,
      indices: [14],
      stats: [
        "SNP: ",
        "34.0% of cats (50 total)",
        "17 cats with substitution E",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 24,
      indices: [17],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution F"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 25,
      indices: [28],
      stats: [
        "SNP: ",
        "28.0% of cats (50 total)",
        "5 cats with substitution H",
        "3 cats with substitution K",
        "3 cats with substitution E",
        "3 cats with substitution Q",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 26,
      indices: [31],
      stats: [
        "SNP: ",
        "46.0% of cats (50 total)",
        "20 cats with substitution T",
        "3 cats with substitution N",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 27,
      indices: [32],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution V"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 28,
      indices: [34],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "5 cats with substitution T",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 29,
      indices: [35],
      stats: [
        "SNP: ",
        "46.0% of cats (50 total)",
        "20 cats with substitution S",
        "3 cats with substitution T",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 30,
      indices: [37],
      stats: [
        "SNP: ",
        "22.0% of cats (50 total)",
        "8 cats with substitution D",
        "3 cats with substitution S",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 32,
      indices: [40],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution V"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 33,
      indices: [43],
      stats: [
        "SNP: ",
        "40.0% of cats (50 total)",
        "5 cats with substitution S",
        "15 cats with substitution F",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 34,
      indices: [44],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "5 cats with substitution L",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 35,
      indices: [46],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution I"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 36,
      indices: [47],
      stats: [
        "SNP: ",
        "16.0% of cats (50 total)",
        "5 cats with substitution V",
        "3 cats with substitution R",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 37,
      indices: [58],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution I"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 38,
      indices: [66],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution M"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 39,
      indices: [70],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution F"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 40,
      indices: [71],
      stats: [
        "SNP: ",
        "22.0% of cats (50 total)",
        "5 cats with substitution V",
        "3 cats with substitution M",
        "3 cats with substitution L",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 41,
      indices: [72],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution A"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 42,
      indices: [73],
      stats: [
        "SNP: ",
        "40.0% of cats (50 total)",
        "17 cats with substitution K",
        "3 cats with substitution T",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 43,
      indices: [74],
      stats: [
        "SNP: ",
        "30.0% of cats (50 total)",
        "9 cats with substitution A",
        "3 cats with substitution F",
        "3 cats with substitution G",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 44,
      indices: [76],
      stats: [
        "SNP:  D/V",
        "6.0% of cats (50 total)",
        "2 cats with substitution V",
        "1 cats with ambiguity D/V",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 45,
      indices: [77],
      stats: [
        "SNP: ",
        "34.0% of cats (50 total)",
        "14 cats with substitution A",
        "3 cats with substitution T",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 46,
      indices: [78],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "5 cats with substitution I",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 47,
      indices: [81],
      stats: [
        "SNP: ",
        "40.0% of cats (50 total)",
        "14 cats with substitution I",
        "6 cats with substitution A",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 48,
      indices: [82],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution A"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 50,
      indices: [84],
      stats: [
        "SNP: ",
        "16.0% of cats (50 total)",
        "8 cats with substitution -",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 51,
      indices: [85],
      stats: [
        "SNP: ",
        "22.0% of cats (50 total)",
        "8 cats with substitution -",
        "3 cats with substitution F",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 52,
      indices: [86],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "5 cats with substitution N",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 53,
      indices: [87],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "2 cats with substitution E",
        "3 cats with substitution V",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 54,
      indices: [88],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "5 cats with substitution V",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 55,
      indices: [90],
      stats: [
        "SNP:  S/I",
        "24.0% of cats (50 total)",
        "11 cats with substitution I",
        "1 cats with ambiguity S/I",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 56,
      indices: [91],
      stats: [
        "SNP: ",
        "34.0% of cats (50 total)",
        "14 cats with substitution V",
        "3 cats with substitution D",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 57,
      indices: [93],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution T"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 58,
      indices: [94],
      stats: [
        "SNP: ",
        "16.0% of cats (50 total)",
        "5 cats with substitution A",
        "3 cats with substitution S",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 59,
      indices: [95],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution E"],
      variant_type: "exotic",
    },
  ],
  conservedRegions: [],
};
