import { Sequence } from "./components/SequenceViz";
export const chain1_sequence: Sequence = {
    residues: [
        { resn: "M", resi: 0, chain: "A" },
        { resn: "K", resi: 1, chain: "A" },
        { resn: "G", resi: 2, chain: "A" },
        { resn: "A", resi: 3, chain: "A" },
        { resn: "R", resi: 4, chain: "A" },
        { resn: "V", resi: 5, chain: "A" },
        { resn: "L", resi: 6, chain: "A" },
        { resn: "V", resi: 7, chain: "A" },
        { resn: "L", resi: 8, chain: "A" },
        { resn: "L", resi: 9, chain: "A" },
        { resn: "W", resi: 10, chain: "A" },
        { resn: "A", resi: 11, chain: "A" },
        { resn: "A", resi: 12, chain: "A" },
        { resn: "L", resi: 13, chain: "A" },
        { resn: "L", resi: 14, chain: "A" },
        { resn: "L", resi: 15, chain: "A" },
        { resn: "I", resi: 16, chain: "A" },
        { resn: "W", resi: 17, chain: "A" },
        { resn: "G", resi: 18, chain: "A" },
        { resn: "G", resi: 19, chain: "A" },
        { resn: "N", resi: 20, chain: "A" },
        { resn: "C", resi: 21, chain: "A" },
        { resn: "E", resi: 22, chain: "A" },
        { resn: "I", resi: 23, chain: "A" },
        { resn: "C", resi: 24, chain: "A" },
        { resn: "P", resi: 25, chain: "A" },
        { resn: "A", resi: 26, chain: "A" },
        { resn: "V", resi: 27, chain: "A" },
        { resn: "K", resi: 28, chain: "A" },
        { resn: "R", resi: 29, chain: "A" },
        { resn: "D", resi: 30, chain: "A" },
        { resn: "V", resi: 31, chain: "A" },
        { resn: "D", resi: 32, chain: "A" },
        { resn: "L", resi: 33, chain: "A" },
        { resn: "F", resi: 34, chain: "A" },
        { resn: "L", resi: 35, chain: "A" },
        { resn: "T", resi: 36, chain: "A" },
        { resn: "G", resi: 37, chain: "A" },
        { resn: "T", resi: 38, chain: "A" },
        { resn: "P", resi: 39, chain: "A" },
        { resn: "D", resi: 40, chain: "A" },
        { resn: "E", resi: 41, chain: "A" },
        { resn: "Y", resi: 42, chain: "A" },
        { resn: "V", resi: 43, chain: "A" },
        { resn: "E", resi: 44, chain: "A" },
        { resn: "Q", resi: 45, chain: "A" },
        { resn: "V", resi: 46, chain: "A" },
        { resn: "A", resi: 47, chain: "A" },
        { resn: "Q", resi: 48, chain: "A" },
        { resn: "Y", resi: 49, chain: "A" },
        { resn: "K", resi: 50, chain: "A" },
        { resn: "A", resi: 51, chain: "A" },
        { resn: "L", resi: 52, chain: "A" },
        { resn: "P", resi: 53, chain: "A" },
        { resn: "V", resi: 54, chain: "A" },
        { resn: "V", resi: 55, chain: "A" },
        { resn: "L", resi: 56, chain: "A" },
        { resn: "E", resi: 57, chain: "A" },
        { resn: "N", resi: 58, chain: "A" },
        { resn: "A", resi: 59, chain: "A" },
        { resn: "R", resi: 60, chain: "A" },
        { resn: "I", resi: 61, chain: "A" },
    ],

    variants: [
        {
            region: {
                indices: [0, 1, 2, 3],
                residues: [
                    { resi: 0, resn: "TYR", chain: "A" },
                    { resi: 1, resn: "TYR", chain: "A" },
                    { resi: 2, resn: "TYR", chain: "A" },
                    { resi: 3, resn: "TYR", chain: "A" },
                ],
            },
            stats: ["stats", "stat1", "stat2", "stat3"],
            variant_type: "domestic",
        },
        {
            region: {
                indices: [10, 11, 12, 13],
                residues: [
                    { resi: 10, resn: "TYR", chain: "A" },
                    { resi: 11, resn: "TYR", chain: "A" },
                    { resi: 12, resn: "TYR", chain: "A" },
                    { resi: 13, resn: "TYR", chain: "A" },
                ],
            },
            stats: ["stats", "stat1", "stat2", "stat3"],
            variant_type: "exotic",
        },
        {
            region: {
                indices: [20, 21, 22, 23],
                residues: [
                    { resi: 20, resn: "TYR", chain: "A" },
                    { resi: 21, resn: "TYR", chain: "A" },
                    { resi: 22, resn: "TYR", chain: "A" },
                    { resi: 23, resn: "TYR", chain: "A" },
                ],
            },
            stats: ["stats", "stat1", "stat2", "stat3"],
            variant_type: "domestic",
        },
        {
            region: {
                indices: [20, 21, 22, 23],
                residues: [
                    { resi: 20, resn: "TYR", chain: "A" },
                    { resi: 21, resn: "TYR", chain: "A" },
                    { resi: 22, resn: "TYR", chain: "A" },
                    { resi: 23, resn: "TYR", chain: "A" },
                ],
            },
            stats: ["stats", "stat1", "stat2", "stat3"],
            variant_type: "exotic",
        },
    ],
    conservedRegions: [
        {
            indices: [7, 8, 9, 10, 11, 12, 13],
            residues: [
                { resn: "V", resi: 7, chain: "A" },
                { resn: "L", resi: 8, chain: "A" },
                { resn: "L", resi: 9, chain: "A" },
                { resn: "W", resi: 10, chain: "A" },
                { resn: "A", resi: 11, chain: "A" },
                { resn: "A", resi: 12, chain: "A" },
                { resn: "L", resi: 13, chain: "A" },
            ],
        },
    ],
};

export const chain2_sequence: Sequence = {
    residues: [
        { resn: "V", resi: 0, chain: "B" },
        { resn: "E", resi: 1, chain: "B" },
        { resn: "Q", resi: 2, chain: "B" },
        { resn: "V", resi: 3, chain: "B" },
        { resn: "B", resi: 4, chain: "B" },
        { resn: "Q", resi: 5, chain: "B" },
        { resn: "Y", resi: 6, chain: "B" },
        { resn: "K", resi: 7, chain: "B" },
        { resn: "B", resi: 8, chain: "B" },
        { resn: "L", resi: 9, chain: "B" },
        { resn: "P", resi: 10, chain: "B" },
        { resn: "V", resi: 11, chain: "B" },
        { resn: "V", resi: 12, chain: "B" },
        { resn: "L", resi: 13, chain: "B" },
        { resn: "E", resi: 14, chain: "B" },
        { resn: "N", resi: 15, chain: "B" },
        { resn: "B", resi: 16, chain: "B" },
        { resn: "R", resi: 17, chain: "B" },
        { resn: "I", resi: 18, chain: "B" },
        { resn: "M", resi: 19, chain: "B" },
        { resn: "K", resi: 20, chain: "B" },
        { resn: "G", resi: 21, chain: "B" },
        { resn: "B", resi: 22, chain: "B" },
        { resn: "R", resi: 23, chain: "B" },
        { resn: "V", resi: 24, chain: "B" },
        { resn: "L", resi: 25, chain: "B" },
        { resn: "V", resi: 26, chain: "B" },
        { resn: "L", resi: 27, chain: "B" },
        { resn: "L", resi: 28, chain: "B" },
        { resn: "W", resi: 29, chain: "B" },
        { resn: "B", resi: 30, chain: "B" },
        { resn: "B", resi: 31, chain: "B" },
        { resn: "L", resi: 32, chain: "B" },
        { resn: "L", resi: 33, chain: "B" },
        { resn: "L", resi: 34, chain: "B" },
        { resn: "I", resi: 35, chain: "B" },
        { resn: "W", resi: 36, chain: "B" },
        { resn: "G", resi: 37, chain: "B" },
        { resn: "G", resi: 38, chain: "B" },
        { resn: "N", resi: 39, chain: "B" },
        { resn: "C", resi: 40, chain: "B" },
        { resn: "E", resi: 41, chain: "B" },
        { resn: "I", resi: 42, chain: "B" },
        { resn: "C", resi: 43, chain: "B" },
        { resn: "P", resi: 44, chain: "B" },
        { resn: "B", resi: 45, chain: "B" },
        { resn: "V", resi: 46, chain: "B" },
        { resn: "K", resi: 47, chain: "B" },
        { resn: "R", resi: 48, chain: "B" },
        { resn: "D", resi: 49, chain: "B" },
        { resn: "V", resi: 50, chain: "B" },
        { resn: "D", resi: 51, chain: "B" },
        { resn: "L", resi: 52, chain: "B" },
        { resn: "F", resi: 53, chain: "B" },
        { resn: "L", resi: 54, chain: "B" },
        { resn: "T", resi: 55, chain: "B" },
        { resn: "G", resi: 56, chain: "B" },
        { resn: "T", resi: 57, chain: "B" },
        { resn: "P", resi: 58, chain: "B" },
        { resn: "D", resi: 59, chain: "B" },
        { resn: "E", resi: 60, chain: "B" },
        { resn: "Y", resi: 61, chain: "B" },
    ],

    variants: [
        {
            region: {
                indices: [0, 1, 2, 3],
                residues: [
                    { resi: 0, resn: "TYR", chain: "B" },
                    { resi: 1, resn: "TYR", chain: "B" },
                    { resi: 2, resn: "TYR", chain: "B" },
                    { resi: 3, resn: "TYR", chain: "B" },
                ],
            },
            stats: ["stats", "stat1", "stat2", "stat3"],
            variant_type: "domestic",
        },
        {
            region: {
                indices: [10, 11, 12, 13],
                residues: [
                    { resi: 10, resn: "TYR", chain: "B" },
                    { resi: 11, resn: "TYR", chain: "B" },
                    { resi: 12, resn: "TYR", chain: "B" },
                    { resi: 13, resn: "TYR", chain: "B" },
                ],
            },
            stats: ["stats", "stat1", "stat2", "stat3"],
            variant_type: "exotic",
        },
        {
            region: {
                indices: [20, 21, 22, 23],
                residues: [
                    { resi: 20, resn: "TYR", chain: "B" },
                    { resi: 21, resn: "TYR", chain: "B" },
                    { resi: 22, resn: "TYR", chain: "B" },
                    { resi: 23, resn: "TYR", chain: "B" },
                ],
            },
            stats: ["stats", "stat1", "stat2", "stat3"],
            variant_type: "domestic",
        },
        {
            region: {
                indices: [20, 21, 22, 23],
                residues: [
                    { resi: 20, resn: "TYR", chain: "B" },
                    { resi: 21, resn: "TYR", chain: "B" },
                    { resi: 22, resn: "TYR", chain: "B" },
                    { resi: 23, resn: "TYR", chain: "B" },
                ],
            },
            stats: ["stats", "stat1", "stat2", "stat3"],
            variant_type: "exotic",
        },
    ],
    conservedRegions: [
        {
            indices: [7, 8, 9, 10, 11, 12, 13],
            residues: [
                { resn: "V", resi: 7, chain: "B" },
                { resn: "L", resi: 8, chain: "B" },
                { resn: "L", resi: 9, chain: "B" },
                { resn: "W", resi: 10, chain: "B" },
                { resn: "B", resi: 11, chain: "B" },
                { resn: "B", resi: 12, chain: "B" },
                { resn: "L", resi: 13, chain: "B" },
            ],
        },
    ],
};
