import { Sequence } from "./components/SequenceViz";
export const chain2_sequence: Sequence = {
    residues: [
        { resi: 0, resn: "M", chain: "B" },
        { resi: 1, resn: "R", chain: "B" },
        { resi: 2, resn: "G", chain: "B" },
        { resi: 3, resn: "A", chain: "B" },
        { resi: 4, resn: "L", chain: "B" },
        { resi: 5, resn: "L", chain: "B" },
        { resi: 6, resn: "V", chain: "B" },
        { resi: 7, resn: "L", chain: "B" },
        { resi: 8, resn: "A", chain: "B" },
        { resi: 9, resn: "L", chain: "B" },
        { resi: 10, resn: "L", chain: "B" },
        { resi: 11, resn: "V", chain: "B" },
        { resi: 12, resn: "T", chain: "B" },
        { resi: 13, resn: "Q", chain: "B" },
        { resi: 14, resn: "A", chain: "B" },
        { resi: 15, resn: "L", chain: "B" },
        { resi: 16, resn: "G", chain: "B" },
        { resi: 17, resn: "V", chain: "B", structureIndex: 71 },
        { resi: 18, resn: "K", chain: "B", structureIndex: 72 },
        { resi: 19, resn: "M", chain: "B", structureIndex: 73 },
        { resi: 20, resn: "A", chain: "B", structureIndex: 74 },
        { resi: 21, resn: "E", chain: "B", structureIndex: 75 },
        { resi: 22, resn: "T", chain: "B", structureIndex: 76 },
        { resi: 23, resn: "C", chain: "B", structureIndex: 77 },
        { resi: 24, resn: "P", chain: "B", structureIndex: 78 },
        { resi: 25, resn: "I", chain: "B", structureIndex: 79 },
        { resi: 26, resn: "F", chain: "B", structureIndex: 80 },
        { resi: 27, resn: "Y", chain: "B", structureIndex: 81 },
        { resi: 28, resn: "D", chain: "B", structureIndex: 82 },
        { resi: 29, resn: "V", chain: "B", structureIndex: 83 },
        { resi: 30, resn: "F", chain: "B", structureIndex: 84 },
        { resi: 31, resn: "F", chain: "B", structureIndex: 85 },
        { resi: 32, resn: "A", chain: "B", structureIndex: 86 },
        { resi: 33, resn: "V", chain: "B", structureIndex: 87 },
        { resi: 34, resn: "A", chain: "B", structureIndex: 88 },
        { resi: 35, resn: "N", chain: "B", structureIndex: 89 },
        { resi: 36, resn: "G", chain: "B", structureIndex: 90 },
        { resi: 37, resn: "N", chain: "B", structureIndex: 91 },
        { resi: 38, resn: "E", chain: "B", structureIndex: 92 },
        { resi: 39, resn: "L", chain: "B", structureIndex: 93 },
        { resi: 40, resn: "L", chain: "B", structureIndex: 94 },
        { resi: 41, resn: "L", chain: "B", structureIndex: 95 },
        { resi: 42, resn: "D", chain: "B", structureIndex: 96 },
        { resi: 43, resn: "L", chain: "B", structureIndex: 97 },
        { resi: 44, resn: "S", chain: "B", structureIndex: 98 },
        { resi: 45, resn: "L", chain: "B", structureIndex: 99 },
        { resi: 46, resn: "T", chain: "B", structureIndex: 100 },
        { resi: 47, resn: "K", chain: "B", structureIndex: 101 },
        { resi: 48, resn: "V", chain: "B", structureIndex: 102 },
        { resi: 49, resn: "N", chain: "B", structureIndex: 103 },
        { resi: 50, resn: "A", chain: "B", structureIndex: 104 },
        { resi: 51, resn: "T", chain: "B", structureIndex: 105 },
        { resi: 52, resn: "E", chain: "B", structureIndex: 106 },
        { resi: 53, resn: "P", chain: "B", structureIndex: 107 },
        { resi: 54, resn: "E", chain: "B", structureIndex: 108 },
        { resi: 55, resn: "R", chain: "B", structureIndex: 109 },
        { resi: 56, resn: "T", chain: "B", structureIndex: 110 },
        { resi: 57, resn: "A", chain: "B", structureIndex: 111 },
        { resi: 58, resn: "M", chain: "B", structureIndex: 112 },
        { resi: 59, resn: "K", chain: "B", structureIndex: 113 },
        { resi: 60, resn: "K", chain: "B", structureIndex: 114 },
        { resi: 61, resn: "I", chain: "B", structureIndex: 115 },
        { resi: 62, resn: "Q", chain: "B", structureIndex: 116 },
        { resi: 63, resn: "D", chain: "B", structureIndex: 117 },
        { resi: 64, resn: "C", chain: "B", structureIndex: 118 },
        { resi: 65, resn: "Y", chain: "B", structureIndex: 119 },
        { resi: 66, resn: "V", chain: "B", structureIndex: 120 },
        { resi: 67, resn: "E", chain: "B", structureIndex: 121 },
        { resi: 68, resn: "N", chain: "B", structureIndex: 122 },
        { resi: 69, resn: "G", chain: "B", structureIndex: 123 },
        { resi: 70, resn: "L", chain: "B", structureIndex: 124 },
        { resi: 71, resn: "I", chain: "B", structureIndex: 125 },
        { resi: 72, resn: "S", chain: "B", structureIndex: 126 },
        { resi: 73, resn: "R", chain: "B", structureIndex: 127 },
        { resi: 74, resn: "V", chain: "B", structureIndex: 128 },
        { resi: 75, resn: "L", chain: "B", structureIndex: 129 },
        { resi: 76, resn: "D", chain: "B", structureIndex: 130 },
        { resi: 77, resn: "G", chain: "B", structureIndex: 131 },
        { resi: 78, resn: "L", chain: "B", structureIndex: 132 },
        { resi: 79, resn: "V", chain: "B", structureIndex: 133 },
        { resi: 80, resn: "M", chain: "B", structureIndex: 134 },
        { resi: 81, resn: "T", chain: "B", structureIndex: 135 },
        { resi: 82, resn: "T", chain: "B", structureIndex: 136 },
        { resi: 83, resn: "I", chain: "B", structureIndex: 137 },
        { resi: 84, resn: "S", chain: "B", structureIndex: 138 },
        { resi: 85, resn: "S", chain: "B", structureIndex: 139 },
        { resi: 86, resn: "S", chain: "B", structureIndex: 140 },
        { resi: 87, resn: "K", chain: "B", structureIndex: 141 },
        { resi: 88, resn: "D", chain: "B", structureIndex: 142 },
        { resi: 89, resn: "C", chain: "B", structureIndex: 143 },
        { resi: 90, resn: "M", chain: "B", structureIndex: 144 },
        { resi: 91, resn: "G", chain: "B", structureIndex: 145 },
        { resi: 92, resn: "E", chain: "B", structureIndex: 146 },
        { resi: 93, resn: "A", chain: "B" },
        { resi: 94, resn: "V", chain: "B" },
        { resi: 95, resn: "Q", chain: "B" },
        { resi: 96, resn: "N", chain: "B" },
        { resi: 97, resn: "T", chain: "B" },
        { resi: 98, resn: "V", chain: "B" },
        { resi: 99, resn: "E", chain: "B" },
        { resi: 100, resn: "D", chain: "B" },
        { resi: 101, resn: "L", chain: "B" },
        { resi: 102, resn: "K", chain: "B" },
        { resi: 103, resn: "L", chain: "B" },
        { resi: 104, resn: "N", chain: "B" },
        { resi: 105, resn: "T", chain: "B" },
        { resi: 106, resn: "L", chain: "B" },
        { resi: 107, resn: "G", chain: "B" },
        { resi: 108, resn: "R", chain: "B" },
    ],
    variants: [
        {
            id: 0,
            indices: [14],
            stats: [
                "SNP: A/E",
                "44.0% of cats (50 total)",
                "13 cats with ambiguity A/E",
                "9 cats with substitution E",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [],
            color: "yellow",
        },
        {
            id: 1,
            indices: [28],
            stats: [
                "SNP: D/E",
                "12.0% of cats (50 total)",
                "6 cats with ambiguity D/E",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [2, 3],
            color: "hotpink",
        },
        {
            id: 2,
            indices: [31],
            stats: [
                "MNP: F/T/S/I",
                "34.0% of cats (50 total)",
                "8 cats with substitution T",
                "8 cats with  F/T/S/I",
                "1 cats with rare mutation T/S",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [3],
            color: "hotpink",
        },
        {
            id: 3,
            indices: [35],
            stats: [
                "SNP: N/S",
                "34.0% of cats (50 total)",
                "8 cats with substitution S",
                "9 cats with ambiguity N/S",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [2],
            color: "hotpink",
        },
        {
            id: 4,
            indices: [37],
            stats: [
                "SNP: N/D",
                "14.0% of cats (50 total)",
                "4 cats with ambiguity N/D",
                "3 cats with substitution D",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [2, 3],
            color: "hotpink",
        },
        {
            id: 5,
            indices: [43],
            stats: [
                "SNP: L/F/S",
                "20.0% of cats (50 total)",
                "10 cats with ambiguity L/F/S",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [9],
            color: "blue",
        },
        {
            id: 6,
            indices: [71],
            stats: [
                "SNP: I/L/V",
                "86.0% of cats (50 total)",
                "12 cats with ambiguity I/V",
                "8 cats with substitution V",
                "8 cats with ambiguity I/L",
                "13 cats with ambiguity V/L",
                "2 cats with substitution L",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [],
            color: "orange",
        },
        {
            id: 7,
            indices: [73],
            stats: [
                "SNP: R/K",
                "66.0% of cats (50 total)",
                "25 cats with ambiguity R/K",
                "8 cats with substitution K",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [8],
            color: "teal",
        },
        {
            id: 8,
            indices: [74],
            stats: [
                "SNP: V/F/A/S",
                "66.0% of cats (50 total)",
                "11 cats with ambiguity V/F",
                "4 cats with ambiguity V/F/A/S",
                "14 cats with ambiguity V/A",
                "4 cats with substitution F",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [7],
            color: "blue",
        },
        {
            id: 9,
            indices: [77],
            stats: [
                "SNP: G/A/T/R",
                "36.0% of cats (50 total)",
                "16 cats with ambiguity G/A/T/R",
                "2 cats with ambiguity G/A",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [7, 8],
            color: "purple",
        },
        {
            id: 10,
            indices: [81],
            stats: [
                "SNP: T/I",
                "64.0% of cats (50 total)",
                "23 cats with substitution I",
                "9 cats with ambiguity T/I",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [11, 12, 13, 14, 15, 16, 17],
            color: "purple",
        },
        {
            id: 11,
            indices: [82],
            stats: [
                "SNP: T/A",
                "42.0% of cats (50 total)",
                "18 cats with substitution A",
                "3 cats with ambiguity T/A",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [10, 12, 13, 14, 15, 16, 17],
            color: "purple",
        },
        {
            id: 12,
            indices: [83],
            stats: ["SNP: I/-", "42.0% of cats (50 total)", "21 cats with abscence"],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [10, 11, 13, 14, 15, 16, 17],
            color: "purple",
        },
        {
            id: 13,
            indices: [84],
            stats: [
                "SNP: S/-",
                "42.0% of cats (50 total)",
                "21 cats with substitution -",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [10, 11, 12, 14, 15, 16, 17],
            color: "purple",
        },
        {
            id: 14,
            indices: [85],
            stats: [
                "SNP: S/-",
                "42.0% of cats (50 total)",
                "21 cats with substitution -",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [10, 11, 12, 13, 15, 16, 17],
            color: "purple",
        },
        {
            id: 15,
            indices: [86],
            stats: [
                "SNP: S/N",
                "42.0% of cats (50 total)",
                "21 cats with substitution N",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [10, 11, 12, 13, 14, 16, 17],
            color: "purple",
        },
        {
            id: 16,
            indices: [87],
            stats: [
                "SNP: V",
                "40.0% of cats (50 total)",
                "13 cats with substitution V",
                "5 cats with substitution E",
                "2 cats with ambiguity E/V",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [10, 11, 12, 13, 14, 15, 17],
            color: "purple",
        },
        {
            id: 17,
            indices: [88],
            stats: [
                "SNP: Y",
                "14.0% of cats (50 total)",
                "2 cats with ambiguity D/Y",
                "5 cats with substitution Y",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [10, 11, 12, 13, 14, 15, 16],
            color: "purple",
        },
        {
            id: 18,
            indices: [90],
            stats: [
                "SNP: M/T",
                "30.0% of cats (50 total)",
                "9 cats with ambiguity M/T",
                "6 cats with substitution T",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [0],
            color: "yellow",
        },
        {
            id: 19,
            indices: [95],
            stats: [
                "SNP: Q/E",
                "34.0% of cats (50 total)",
                "4 cats with ambiguity Q/E",
                "13 cats with substitution E",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [20],
            color: "mediumpurple",
        },
        {
            id: 20,
            indices: [104],
            stats: [
                "SNP: N/K",
                "34.0% of cats (50 total)",
                "4 cats with ambiguity N/K",
                "13 cats with substitution K",
            ],
            chain: "B",
            variant_type: "domestic",
            correlated_ids: [19],
            color: "mediumpurple",
        },
    ],
    conservedRegions: [],
};
