import { Sequence } from "./components/SequenceViz";
export const chain2_sequence: Sequence = {
  residues: [
    { resi: 0, resn: "M", chain: "B" },
    { resi: 1, resn: "R", chain: "B" },
    { resi: 2, resn: "G", chain: "B" },
    { resi: 3, resn: "A", chain: "B" },
    { resi: 4, resn: "L", chain: "B" },
    { resi: 5, resn: "L", chain: "B" },
    { resi: 6, resn: "V", chain: "B" },
    { resi: 7, resn: "L", chain: "B" },
    { resi: 8, resn: "A", chain: "B" },
    { resi: 9, resn: "L", chain: "B" },
    { resi: 10, resn: "L", chain: "B" },
    { resi: 11, resn: "V", chain: "B" },
    { resi: 12, resn: "T", chain: "B" },
    { resi: 13, resn: "Q", chain: "B" },
    { resi: 14, resn: "A", chain: "B" },
    { resi: 15, resn: "L", chain: "B" },
    { resi: 16, resn: "G", chain: "B" },
    { resi: 17, resn: "V", chain: "B", structureIndex: 71 },
    { resi: 18, resn: "K", chain: "B", structureIndex: 72 },
    { resi: 19, resn: "M", chain: "B", structureIndex: 73 },
    { resi: 20, resn: "A", chain: "B", structureIndex: 74 },
    { resi: 21, resn: "E", chain: "B", structureIndex: 75 },
    { resi: 22, resn: "T", chain: "B", structureIndex: 76 },
    { resi: 23, resn: "C", chain: "B", structureIndex: 77 },
    { resi: 24, resn: "P", chain: "B", structureIndex: 78 },
    { resi: 25, resn: "I", chain: "B", structureIndex: 79 },
    { resi: 26, resn: "F", chain: "B", structureIndex: 80 },
    { resi: 27, resn: "Y", chain: "B", structureIndex: 81 },
    { resi: 28, resn: "D", chain: "B", structureIndex: 82 },
    { resi: 29, resn: "V", chain: "B", structureIndex: 83 },
    { resi: 30, resn: "F", chain: "B", structureIndex: 84 },
    { resi: 31, resn: "F", chain: "B", structureIndex: 85 },
    { resi: 32, resn: "A", chain: "B", structureIndex: 86 },
    { resi: 33, resn: "V", chain: "B", structureIndex: 87 },
    { resi: 34, resn: "A", chain: "B", structureIndex: 88 },
    { resi: 35, resn: "N", chain: "B", structureIndex: 89 },
    { resi: 36, resn: "G", chain: "B", structureIndex: 90 },
    { resi: 37, resn: "N", chain: "B", structureIndex: 91 },
    { resi: 38, resn: "E", chain: "B", structureIndex: 92 },
    { resi: 39, resn: "L", chain: "B", structureIndex: 93 },
    { resi: 40, resn: "L", chain: "B", structureIndex: 94 },
    { resi: 41, resn: "L", chain: "B", structureIndex: 95 },
    { resi: 42, resn: "D", chain: "B", structureIndex: 96 },
    { resi: 43, resn: "L", chain: "B", structureIndex: 97 },
    { resi: 44, resn: "S", chain: "B", structureIndex: 98 },
    { resi: 45, resn: "L", chain: "B", structureIndex: 99 },
    { resi: 46, resn: "T", chain: "B", structureIndex: 100 },
    { resi: 47, resn: "K", chain: "B", structureIndex: 101 },
    { resi: 48, resn: "V", chain: "B", structureIndex: 102 },
    { resi: 49, resn: "N", chain: "B", structureIndex: 103 },
    { resi: 50, resn: "A", chain: "B", structureIndex: 104 },
    { resi: 51, resn: "T", chain: "B", structureIndex: 105 },
    { resi: 52, resn: "E", chain: "B", structureIndex: 106 },
    { resi: 53, resn: "P", chain: "B", structureIndex: 107 },
    { resi: 54, resn: "E", chain: "B", structureIndex: 108 },
    { resi: 55, resn: "R", chain: "B", structureIndex: 109 },
    { resi: 56, resn: "T", chain: "B", structureIndex: 110 },
    { resi: 57, resn: "A", chain: "B", structureIndex: 111 },
    { resi: 58, resn: "M", chain: "B", structureIndex: 112 },
    { resi: 59, resn: "K", chain: "B", structureIndex: 113 },
    { resi: 60, resn: "K", chain: "B", structureIndex: 114 },
    { resi: 61, resn: "I", chain: "B", structureIndex: 115 },
    { resi: 62, resn: "Q", chain: "B", structureIndex: 116 },
    { resi: 63, resn: "D", chain: "B", structureIndex: 117 },
    { resi: 64, resn: "C", chain: "B", structureIndex: 118 },
    { resi: 65, resn: "Y", chain: "B", structureIndex: 119 },
    { resi: 66, resn: "V", chain: "B", structureIndex: 120 },
    { resi: 67, resn: "E", chain: "B", structureIndex: 121 },
    { resi: 68, resn: "N", chain: "B", structureIndex: 122 },
    { resi: 69, resn: "G", chain: "B", structureIndex: 123 },
    { resi: 70, resn: "L", chain: "B", structureIndex: 124 },
    { resi: 71, resn: "I", chain: "B", structureIndex: 125 },
    { resi: 72, resn: "S", chain: "B", structureIndex: 126 },
    { resi: 73, resn: "R", chain: "B", structureIndex: 127 },
    { resi: 74, resn: "V", chain: "B", structureIndex: 128 },
    { resi: 75, resn: "L", chain: "B", structureIndex: 129 },
    { resi: 76, resn: "D", chain: "B", structureIndex: 130 },
    { resi: 77, resn: "G", chain: "B", structureIndex: 131 },
    { resi: 78, resn: "L", chain: "B", structureIndex: 132 },
    { resi: 79, resn: "V", chain: "B", structureIndex: 133 },
    { resi: 80, resn: "M", chain: "B", structureIndex: 134 },
    { resi: 81, resn: "T", chain: "B", structureIndex: 135 },
    { resi: 82, resn: "T", chain: "B", structureIndex: 136 },
    { resi: 83, resn: "I", chain: "B", structureIndex: 137 },
    { resi: 84, resn: "S", chain: "B", structureIndex: 138 },
    { resi: 85, resn: "S", chain: "B", structureIndex: 139 },
    { resi: 86, resn: "S", chain: "B", structureIndex: 140 },
    { resi: 87, resn: "K", chain: "B", structureIndex: 141 },
    { resi: 88, resn: "D", chain: "B", structureIndex: 142 },
    { resi: 89, resn: "C", chain: "B", structureIndex: 143 },
    { resi: 90, resn: "M", chain: "B", structureIndex: 144 },
    { resi: 91, resn: "G", chain: "B", structureIndex: 145 },
    { resi: 92, resn: "E", chain: "B", structureIndex: 146 },
    { resi: 93, resn: "A", chain: "B" },
    { resi: 94, resn: "V", chain: "B" },
    { resi: 95, resn: "Q", chain: "B" },
    { resi: 96, resn: "N", chain: "B" },
    { resi: 97, resn: "T", chain: "B" },
    { resi: 98, resn: "V", chain: "B" },
    { resi: 99, resn: "E", chain: "B" },
    { resi: 100, resn: "D", chain: "B" },
    { resi: 101, resn: "L", chain: "B" },
    { resi: 102, resn: "K", chain: "B" },
    { resi: 103, resn: "L", chain: "B" },
    { resi: 104, resn: "N", chain: "B" },
    { resi: 105, resn: "T", chain: "B" },
    { resi: 106, resn: "L", chain: "B" },
    { resi: 107, resn: "G", chain: "B" },
    { resi: 108, resn: "R", chain: "B" },
  ],
  variants: [
    {
      chain: "A",
      color: "#ffff00",
      correlated_ids: [16],
      id: 0,
      indices: [14],
      stats: ["A → E", "44% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#d60093",
      correlated_ids: [2, 3],
      id: 1,
      indices: [28],
      stats: ["D → E", "12% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#d60093",
      correlated_ids: [1, 3],
      id: 2,
      indices: [36],
      stats: ["N → S", "34% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#d60093",
      correlated_ids: [1, 2],
      id: 3,
      indices: [38],
      stats: ["N → D", "14% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#3366ff",
      correlated_ids: [8],
      id: 4,
      indices: [44],
      stats: ["L → L or F or S", "20% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#ff9933",
      correlated_ids: [],
      id: 5,
      indices: [72],
      stats: ["I → L or V", "20% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [7],
      id: 6,
      indices: [74],
      stats: ["R → K", "66% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [6],
      id: 7,
      indices: [75],
      stats: [
        "V → F or A or S",
        "(F) 30% of domestic cats\n",
        "(S) 8 % of domestic cats\n",
        "(A) 28% of domestic cats",
      ],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#3366ff",
      correlated_ids: [4],
      id: 8,
      indices: [78],
      stats: [
        "G → A or T or R",
        "(A) 4% of domestic cats\n(T or R) 32% of domestic cats",
      ],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#7030a0",
      correlated_ids: [10, 11, 12, 13, 14, 15],
      id: 9,
      indices: [82],
      stats: ["T → I", "64% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#7030a0",
      correlated_ids: [9, 11, 12, 13, 14, 15],
      id: 10,
      indices: [83],
      stats: ["T → A", "44% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#7030a0",
      correlated_ids: [9, 10, 12, 13, 14, 15],
      id: 11,
      indices: [85],
      stats: ["S → -", "42% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#7030a0",
      correlated_ids: [9, 10, 11, 13, 14, 15],
      id: 12,
      indices: [86],
      stats: ["S → -", "42% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#7030a0",
      correlated_ids: [9, 10, 11, 12, 14, 15],
      id: 13,
      indices: [87],
      stats: ["S → N", "42% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#7030a0",
      correlated_ids: [9, 10, 11, 12, 13, 15],
      id: 14,
      indices: [88],
      stats: ["K → E", "10% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#7030a0",
      correlated_ids: [9, 10, 11, 12, 13, 14],
      id: 15,
      indices: [89],
      stats: ["D → Y", "16% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#ffff00",
      correlated_ids: [0],
      id: 16,
      indices: [91],
      stats: ["M → T", "30% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#ccccff",
      correlated_ids: [18],
      id: 17,
      indices: [96],
      stats: ["Q → E", "34% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#ccccff",
      correlated_ids: [17],
      id: 18,
      indices: [105],
      stats: ["N → K", "34% of domestic cats"],
      variant_type: "domestic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 19,
      indices: [8],
      stats: [
        "A → T",
        "12.5% of exotic cats analyzed",
        "Species: Chinese mountain cat",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 20,
      indices: [13],
      stats: ["Q → R", "12.5% of exotic cats analyzed", "Species: Cougar"],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 21,
      indices: [14],
      stats: [
        "A → E",
        "75% of exotic cats analyzed",
        "Species: Cougar, Iberian lynx, African lion, Bengal tiger, ",
        "leopard cat, fishing cat",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 22,
      indices: [17],
      stats: [
        "V → F",
        "12.5% of exotic cats analyzed",
        "Species: Iberian lynx",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 23,
      indices: [28],
      stats: [
        "D → E/H/K/Q",
        "12.5% of exotic cats analyzed (E)\n",
        "25% of exotic cats analyzed (H)\n",
        "12.5% of exotic cats analyzed (K)\n",
        "12.5% of exotic cats analyzed (Q)",
        "Species: Chinese mountain cat (E)\n",
        "Cougar, Bengal tiger (H)\n",

        "Black-footed cat (K)\n",

        "African lion (Q)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 24,
      indices: [31],
      stats: [
        "F → T/N",
        "87.5% of exotic cats analyzed (T)\n",
        "12.5% of exotic cats analyzed (N)",
        "Species: Cougar, black-footed cat, Iberian lynx, African lion, ",
        "Bengal tiger, leopard cat, fishing cat (T)\n",
        "Chinese mountain cat (N)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 25,
      indices: [32],
      stats: [
        "A → V",
        "12.5% of exotic cats analyzed",
        "Species: African lion",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 26,
      indices: [34],
      stats: [
        "A → T",
        "25% of exotic cats analyzed",
        "Species: African lion, Bengal tiger",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 27,
      indices: [35],
      stats: [
        "N → S/T",
        "87.5% of exotic cats analyzed (S)\n",
        "12.5% of exotic cats analyzed (T)",
        "Species: Cougar, black-footed cat, Chinese mountain cat, Iberian ",
        "lynx, Bengal tiger, leopard cat, fishing cat (S)\n",
        "African lion (T)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 28,
      indices: [37],
      stats: [
        "N → D/S",
        "37.5% of exotic cats analyzed (D)\n",
        "12.5% of exotic cats analyzed (S)",
        "Species: Cougar, black-footed cat, Chinese mountain cat (D)\n",
        "Iberian lynx (S)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 29,
      indices: [39],
      stats: [
        "L → F",
        "4.2% of exotic cats analyzed (one individual)",
        "Species: Cougar",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 30,
      indices: [40],
      stats: [
        "L → V",
        "12.5% of exotic cats analyzed",
        "Species: Bengal tiger",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 31,
      indices: [43],
      stats: [
        "L → F/S",
        "62.5% of exotic cats analyzed (F)\n",
        "25% of exotic cats analyzed (S)",
        "Species: Black-footed cat, African lion, Bengal tiger, leopard ",
        "cat, fishing cat (F)\n",
        "Cougar, Iberian lynx (S)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 32,
      indices: [44],
      stats: [
        "S → L",
        "25% of exotic cats analyzed",
        "Species: African lion, Bengal tiger",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 33,
      indices: [46],
      stats: ["T → I", "12.5% of exotic cats analyzed", "Species: Fishing cat"],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 34,
      indices: [47],
      stats: [
        "K → V/R",
        "25% of exotic cats analyzed (V)\n",
        "12.5% of exotic cats analyzed (R)",
        "Species: African lion, Bengal tiger (V)\nFishing cat (R)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 35,
      indices: [58],
      stats: [
        "M → I",
        "12.5% of exotic cats analyzed",
        "Species: Iberian lynx",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        37,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 36,
      indices: [66],
      stats: [
        "V → M",
        "12.5% of exotic cats analyzed",
        "Species: African lion",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        39,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 37,
      indices: [70],
      stats: [
        "L → F",
        "12.5% of exotic cats analyzed",
        "Species: Chinese mountain cat",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 38,
      indices: [71],
      stats: [
        "I → L/V/M",
        "12.5% of exotic cats analyzed (L)\n",
        "25% of exotic cats analyzed (V)\n",
        "12.5% of exotic cats analyzed (M)\n",
        "Species: Fishing cat (L)\n",
        "Black-footed cat, Iberian lynx (V)\n",
        "African lion (M)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        42,
        44,
        53,
        54,
        55,
      ],
      id: 39,
      indices: [72],
      stats: [
        "S → A",
        "12.5% of exotic cats analyzed",
        "Species: African lion",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 40,
      indices: [73],
      stats: [
        "R → K/T",
        "75% of exotic cats analyzed (K)\n",
        "12.5% of exotic cats analyzed (T)",
        "Species: Cougar, black-footed cat, Chinese mountain cat, African ",
        "lion, Bengal tiger, leopard cat, fishing cat (K)\n",
        "Iberian lynx (T)\n",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 41,
      indices: [74],
      stats: [
        "V → F/A/G",
        "12.5% of exotic cats analyzed (F)\n",
        "41.7% of exotic cats analyzed (A)\n",
        "12.5% of exotic cats analyzed (G)",
        "Species: Chinese mountain cat (F)\n",
        "Cougar, black-footed cat, African lion, leopard cat (A)\n",
        "Iberian lynx (G)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        44,
        53,
        54,
        55,
      ],
      id: 42,
      indices: [76],
      stats: [
        "D → V",
        "12.5% of exotic cats analyzed",
        "Species: African lion",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 43,
      indices: [77],
      stats: [
        "G → A/T",
        "62.5% of exotic cats analyzed (A)\n",
        "12.5% of exotic cats analyzed (T)",
        "Species: Cougar, Iberian lynx, African lion, leopard cat, fishing ",
        "cat (A)\n",
        "Black-footed cat (T)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        53,
        54,
        55,
      ],
      id: 44,
      indices: [78],
      stats: [
        "L → I",
        "25% of exotic cats analyzed",
        "Species: African lion, Bengal tiger",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 45,
      indices: [81],
      stats: [
        "T → I/A",
        "62.5% of exotic cats analyzed (I)\n",
        "25% of exotic cats analyzed (A)",
        "Species: Cougar, black-footed cat, Chinese mountain cat, Iberian ",
        "lynx, leopard cat (T)\n",
        "Bengal tiger, fishing cat (A)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        47,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 46,
      indices: [82],
      stats: [
        "T → A",
        "12.5% of exotic cats analyzed",
        "Species: Black-footed cat",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        48,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 47,
      indices: [84],
      stats: [
        "S → -",
        "37.5% of exotic cats analyzed",
        "Species: Black-footed cat, Chinese mountain cat, fishing cat",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        49,
        50,
        51,
        52,
        56,
      ],
      id: 48,
      indices: [85],
      stats: [
        "S → -/F",
        "37.5% of exotic cats analyzed (-)\n",
        "12.5% of exotic cats analyzed (F)",
        "Species: Black-footed cat, Chinese mountain cat, fishing cat (-)\n",
        "African lion (F)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        50,
        51,
        52,
        56,
      ],
      id: 49,
      indices: [86],
      stats: [
        "S → N",
        "25% of exotic cats analyzed",
        "Species: Black-footed cat, Chinese mountain cat",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        51,
        52,
        56,
      ],
      id: 50,
      indices: [87],
      stats: [
        "K → E/V",
        "12.5% of exotic cats analyzed (E)\n",
        "12.5% of exotic cats analyzed (V)",
        "Species: Black-footed cat (E)\nChinese mountain cat (V)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        52,
        56,
      ],
      id: 51,
      indices: [88],
      stats: [
        "D → V",
        "25% of exotic cats analyzed",
        "Species: African lion, fishing cat",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        56,
      ],
      id: 52,
      indices: [90],
      stats: [
        "M → I",
        "50% of exotic cats analyzed",
        "Species: Cougar, Iberian lynx, leopard cat, fishing cat",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        54,
        55,
      ],
      id: 53,
      indices: [91],
      stats: [
        "G → V/D",
        "62.5% of exotic cats analyzed (V)\n",
        "12.5% of exotic cats analyzed (D)",
        "Species: Cougar, Chinese mountain cat, Iberian lynx, leopard cat, ",
        "fishing cat (V)\n",
        "African lion (D)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        55,
      ],
      id: 54,
      indices: [93],
      stats: ["A → T", "12.5% of exotic cats analyzed", "Species: Fishing cat"],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#65e6e9",
      correlated_ids: [
        19,
        20,
        22,
        25,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        36,
        37,
        39,
        42,
        44,
        53,
        54,
      ],
      id: 55,
      indices: [94],
      stats: [
        "V → A/S",
        "25% of exotic cats analyzed (A)\n",
        "12.5% of exotic cats analyzed (S)",
        "Species: African lion, Bengal tiger (A)\nFishing cat (S)",
      ],
      variant_type: "exotic",
    },
    {
      chain: "A",
      color: "#00b050",
      correlated_ids: [
        21,
        23,
        24,
        27,
        28,
        31,
        38,
        40,
        41,
        43,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
      ],
      id: 56,
      indices: [95],
      stats: [
        "Q → E",
        "12.5% of exotic cats analyzed",
        "Species: Black-footed cat",
      ],
      variant_type: "exotic",
    },
  ],
  conservedRegions: [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
  ],
};
