import { Sequence } from "./components/SequenceViz";
export const chain1_sequence: Sequence = {
  residues: [
    { resi: 0, resn: "M", chain: "A" },
    { resi: 1, resn: "K", chain: "A" },
    { resi: 2, resn: "G", chain: "A" },
    { resi: 3, resn: "A", chain: "A" },
    { resi: 4, resn: "R", chain: "A" },
    { resi: 5, resn: "V", chain: "A" },
    { resi: 6, resn: "L", chain: "A" },
    { resi: 7, resn: "V", chain: "A" },
    { resi: 8, resn: "L", chain: "A" },
    { resi: 9, resn: "L", chain: "A" },
    { resi: 10, resn: "W", chain: "A" },
    { resi: 11, resn: "A", chain: "A" },
    { resi: 12, resn: "A", chain: "A" },
    { resi: 13, resn: "L", chain: "A" },
    { resi: 14, resn: "L", chain: "A" },
    { resi: 15, resn: "L", chain: "A" },
    { resi: 16, resn: "I", chain: "A" },
    { resi: 17, resn: "W", chain: "A" },
    { resi: 18, resn: "G", chain: "A" },
    { resi: 19, resn: "G", chain: "A" },
    { resi: 20, resn: "N", chain: "A" },
    { resi: 21, resn: "C", chain: "A" },
    { resi: 22, resn: "E", chain: "A", structureIndex: 1 },
    { resi: 23, resn: "I", chain: "A", structureIndex: 2 },
    { resi: 24, resn: "C", chain: "A", structureIndex: 3 },
    { resi: 25, resn: "P", chain: "A", structureIndex: 4 },
    { resi: 26, resn: "A", chain: "A", structureIndex: 5 },
    { resi: 27, resn: "V", chain: "A", structureIndex: 6 },
    { resi: 28, resn: "K", chain: "A", structureIndex: 7 },
    { resi: 29, resn: "R", chain: "A", structureIndex: 8 },
    { resi: 30, resn: "D", chain: "A", structureIndex: 9 },
    { resi: 31, resn: "V", chain: "A", structureIndex: 10 },
    { resi: 32, resn: "D", chain: "A", structureIndex: 11 },
    { resi: 33, resn: "L", chain: "A", structureIndex: 12 },
    { resi: 34, resn: "F", chain: "A", structureIndex: 13 },
    { resi: 35, resn: "L", chain: "A", structureIndex: 14 },
    { resi: 36, resn: "T", chain: "A", structureIndex: 15 },
    { resi: 37, resn: "G", chain: "A", structureIndex: 16 },
    { resi: 38, resn: "T", chain: "A", structureIndex: 17 },
    { resi: 39, resn: "P", chain: "A", structureIndex: 18 },
    { resi: 40, resn: "D", chain: "A", structureIndex: 19 },
    { resi: 41, resn: "E", chain: "A", structureIndex: 20 },
    { resi: 42, resn: "Y", chain: "A", structureIndex: 21 },
    { resi: 43, resn: "V", chain: "A", structureIndex: 22 },
    { resi: 44, resn: "E", chain: "A", structureIndex: 23 },
    { resi: 45, resn: "Q", chain: "A", structureIndex: 24 },
    { resi: 46, resn: "V", chain: "A", structureIndex: 25 },
    { resi: 47, resn: "A", chain: "A", structureIndex: 26 },
    { resi: 48, resn: "Q", chain: "A", structureIndex: 27 },
    { resi: 49, resn: "Y", chain: "A", structureIndex: 28 },
    { resi: 50, resn: "K", chain: "A", structureIndex: 29 },
    { resi: 51, resn: "A", chain: "A", structureIndex: 30 },
    { resi: 52, resn: "L", chain: "A", structureIndex: 31 },
    { resi: 53, resn: "P", chain: "A", structureIndex: 32 },
    { resi: 54, resn: "V", chain: "A", structureIndex: 33 },
    { resi: 55, resn: "V", chain: "A", structureIndex: 34 },
    { resi: 56, resn: "L", chain: "A", structureIndex: 35 },
    { resi: 57, resn: "E", chain: "A", structureIndex: 36 },
    { resi: 58, resn: "N", chain: "A", structureIndex: 37 },
    { resi: 59, resn: "A", chain: "A", structureIndex: 38 },
    { resi: 60, resn: "R", chain: "A", structureIndex: 39 },
    { resi: 61, resn: "I", chain: "A", structureIndex: 40 },
    { resi: 62, resn: "L", chain: "A", structureIndex: 41 },
    { resi: 63, resn: "K", chain: "A", structureIndex: 42 },
    { resi: 64, resn: "N", chain: "A", structureIndex: 43 },
    { resi: 65, resn: "C", chain: "A", structureIndex: 44 },
    { resi: 66, resn: "V", chain: "A", structureIndex: 45 },
    { resi: 67, resn: "D", chain: "A", structureIndex: 46 },
    { resi: 68, resn: "A", chain: "A", structureIndex: 47 },
    { resi: 69, resn: "K", chain: "A", structureIndex: 48 },
    { resi: 70, resn: "M", chain: "A", structureIndex: 49 },
    { resi: 71, resn: "T", chain: "A", structureIndex: 50 },
    { resi: 72, resn: "E", chain: "A", structureIndex: 51 },
    { resi: 73, resn: "E", chain: "A", structureIndex: 52 },
    { resi: 74, resn: "D", chain: "A", structureIndex: 53 },
    { resi: 75, resn: "K", chain: "A", structureIndex: 54 },
    { resi: 76, resn: "E", chain: "A", structureIndex: 55 },
    { resi: 77, resn: "N", chain: "A", structureIndex: 56 },
    { resi: 78, resn: "A", chain: "A", structureIndex: 57 },
    { resi: 79, resn: "L", chain: "A", structureIndex: 58 },
    { resi: 80, resn: "S", chain: "A", structureIndex: 59 },
    { resi: 81, resn: "L", chain: "A", structureIndex: 60 },
    { resi: 82, resn: "L", chain: "A", structureIndex: 61 },
    { resi: 83, resn: "D", chain: "A", structureIndex: 62 },
    { resi: 84, resn: "K", chain: "A", structureIndex: 63 },
    { resi: 85, resn: "I", chain: "A", structureIndex: 64 },
    { resi: 86, resn: "Y", chain: "A", structureIndex: 65 },
    { resi: 87, resn: "T", chain: "A", structureIndex: 66 },
    { resi: 88, resn: "S", chain: "A", structureIndex: 67 },
    { resi: 89, resn: "P", chain: "A", structureIndex: 68 },
    { resi: 90, resn: "L", chain: "A", structureIndex: 69 },
    { resi: 91, resn: "C", chain: "A", structureIndex: 70 },
  ],
  variants: [
    {
      id: 0,
      indices: [4],
      stats: [
        "SNP: R/C",
        "20.0% of cats (50 total)",
        "10 cats with ambiguity R/C",
      ],
      variant_type: "domestic",
      correlated_ids: [1, 4, 8],
    },
    {
      id: 1,
      indices: [17],
      stats: [
        "SNP: W/S",
        "24.0% of cats (50 total)",
        "10 cats with ambiguity W/S",
        "2 cats with substitution S",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 2,
      indices: [36],
      stats: [
        "Rare Mutation: T/M",
        "2.0% of cats (50 total)",
        "1 cats with rare mutation M",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 3,
      indices: [41],
      stats: [
        "Rare Mutation: E/K",
        "2.0% of cats (50 total)",
        "1 cats with rare mutation K",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 4,
      indices: [50],
      stats: [
        "SNP: K/N",
        "28.0% of cats (50 total)",
        "11 cats with ambiguity K/N",
        "3 cats with substitution N",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 5,
      indices: [52],
      stats: [
        "Rare Mutation: L/R",
        "2.0% of cats (50 total)",
        "1 cats with rare mutation L/R",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 6,
      indices: [57],
      stats: [
        "Rare Mutation: E/A",
        "2.0% of cats (50 total)",
        "1 cats with rare mutation A",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 7,
      indices: [61],
      stats: [
        "Rare Mutation: I/N",
        "2.0% of cats (50 total)",
        "1 cats with rare mutation N",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 8,
      indices: [81],
      stats: [
        "Rare Mutation: L/V",
        "26.0% of cats (50 total)",
        "12 cats with rare mutation L/V",
        "1 cats with substitution V",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      id: 9,
      indices: [88],
      stats: [
        "Rare Mutation: S/N",
        "2.0% of cats (50 total)",
        "1 cats with rare mutation N",
      ],
      variant_type: "domestic",
      correlated_ids: [],
    },
    {
      correlated_ids: [],
      id: 10,
      indices: [1],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution E"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 11,
      indices: [4],
      stats: [
        "SNP: ",
        "16.0% of cats (50 total)",
        "2 cats with substitution H",
        "6 cats with substitution C",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 12,
      indices: [17],
      stats: [
        "SNP: ",
        "46.0% of cats (50 total)",
        "23 cats with substitution S",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 13,
      indices: [25],
      stats: [
        "SNP: ",
        "22.0% of cats (50 total)",
        "11 cats with substitution S",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 14,
      indices: [30],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "2 cats with substitution I",
        "3 cats with substitution N",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 15,
      indices: [50],
      stats: [
        "SNP: ",
        "46.0% of cats (50 total)",
        "20 cats with substitution N",
        "3 cats with substitution S",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 16,
      indices: [51],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "5 cats with substitution T",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 17,
      indices: [52],
      stats: [
        "SNP: ",
        "34.0% of cats (50 total)",
        "8 cats with substitution R",
        "3 cats with substitution S",
        "6 cats with substitution E",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 18,
      indices: [53],
      stats: [
        "SNP: ",
        "28.0% of cats (50 total)",
        "14 cats with substitution S",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 19,
      indices: [54],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "5 cats with substitution E",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 20,
      indices: [57],
      stats: [
        "SNP: ",
        "26.0% of cats (50 total)",
        "5 cats with substitution A",
        "6 cats with substitution D",
        "2 cats with substitution K",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 21,
      indices: [61],
      stats: [
        "SNP: ",
        "28.0% of cats (50 total)",
        "5 cats with substitution K",
        "3 cats with substitution N",
        "6 cats with substitution T",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 22,
      indices: [66],
      stats: [
        "SNP: ",
        "8.0% of cats (50 total)",
        "1 cats with substitution I",
        "3 cats with substitution A",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 23,
      indices: [75],
      stats: ["SNP: ", "4.0% of cats (50 total)", "2 cats with substitution T"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 24,
      indices: [81],
      stats: [
        "SNP: ",
        "22.0% of cats (50 total)",
        "11 cats with substitution V",
      ],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 25,
      indices: [84],
      stats: ["SNP: ", "2.0% of cats (50 total)", "1 cats with substitution R"],
      variant_type: "exotic",
    },
    {
      correlated_ids: [],
      id: 26,
      indices: [90],
      stats: [
        "SNP: ",
        "10.0% of cats (50 total)",
        "5 cats with substitution G",
      ],
      variant_type: "exotic",
    },
  ],

  conservedRegions: [],
};
