import { Sequence } from "./components/SequenceViz";
export const chain1_sequence: Sequence = {
  residues: [
    { resi: 0, resn: "M", chain: "A" },
    { resi: 1, resn: "K", chain: "A" },
    { resi: 2, resn: "G", chain: "A" },
    { resi: 3, resn: "A", chain: "A" },
    { resi: 4, resn: "R", chain: "A" },
    { resi: 5, resn: "V", chain: "A" },
    { resi: 6, resn: "L", chain: "A" },
    { resi: 7, resn: "V", chain: "A" },
    { resi: 8, resn: "L", chain: "A" },
    { resi: 9, resn: "L", chain: "A" },
    { resi: 10, resn: "W", chain: "A" },
    { resi: 11, resn: "A", chain: "A" },
    { resi: 12, resn: "A", chain: "A" },
    { resi: 13, resn: "L", chain: "A" },
    { resi: 14, resn: "L", chain: "A" },
    { resi: 15, resn: "L", chain: "A" },
    { resi: 16, resn: "I", chain: "A" },
    { resi: 17, resn: "W", chain: "A" },
    { resi: 18, resn: "G", chain: "A" },
    { resi: 19, resn: "G", chain: "A" },
    { resi: 20, resn: "N", chain: "A" },
    { resi: 21, resn: "C", chain: "A" },
    { resi: 22, resn: "E", chain: "A" },
    { resi: 23, resn: "I", chain: "A" },
    { resi: 24, resn: "C", chain: "A" },
    { resi: 25, resn: "P", chain: "A" },
    { resi: 26, resn: "A", chain: "A" },
    { resi: 27, resn: "V", chain: "A" },
    { resi: 28, resn: "K", chain: "A" },
    { resi: 29, resn: "R", chain: "A" },
    { resi: 30, resn: "D", chain: "A" },
    { resi: 31, resn: "V", chain: "A" },
    { resi: 32, resn: "D", chain: "A" },
    { resi: 33, resn: "L", chain: "A" },
    { resi: 34, resn: "F", chain: "A" },
    { resi: 35, resn: "L", chain: "A" },
    { resi: 36, resn: "T", chain: "A" },
    { resi: 37, resn: "G", chain: "A" },
    { resi: 38, resn: "T", chain: "A" },
    { resi: 39, resn: "P", chain: "A" },
    { resi: 40, resn: "D", chain: "A" },
    { resi: 41, resn: "E", chain: "A" },
    { resi: 42, resn: "Y", chain: "A" },
    { resi: 43, resn: "V", chain: "A" },
    { resi: 44, resn: "E", chain: "A" },
    { resi: 45, resn: "Q", chain: "A" },
    { resi: 46, resn: "V", chain: "A" },
    { resi: 47, resn: "A", chain: "A" },
    { resi: 48, resn: "Q", chain: "A" },
    { resi: 49, resn: "Y", chain: "A" },
    { resi: 50, resn: "K", chain: "A" },
    { resi: 51, resn: "A", chain: "A" },
    { resi: 52, resn: "L", chain: "A" },
    { resi: 53, resn: "P", chain: "A" },
    { resi: 54, resn: "V", chain: "A" },
    { resi: 55, resn: "V", chain: "A" },
    { resi: 56, resn: "L", chain: "A" },
    { resi: 57, resn: "E", chain: "A" },
    { resi: 58, resn: "N", chain: "A" },
    { resi: 59, resn: "A", chain: "A" },
    { resi: 60, resn: "R", chain: "A" },
    { resi: 61, resn: "I", chain: "A" },
    { resi: 62, resn: "L", chain: "A" },
    { resi: 63, resn: "K", chain: "A" },
    { resi: 64, resn: "N", chain: "A" },
    { resi: 65, resn: "C", chain: "A" },
    { resi: 66, resn: "V", chain: "A" },
    { resi: 67, resn: "D", chain: "A" },
    { resi: 68, resn: "A", chain: "A" },
    { resi: 69, resn: "K", chain: "A" },
    { resi: 70, resn: "M", chain: "A" },
    { resi: 71, resn: "T", chain: "A" },
    { resi: 72, resn: "E", chain: "A" },
    { resi: 73, resn: "E", chain: "A" },
    { resi: 74, resn: "D", chain: "A" },
    { resi: 75, resn: "K", chain: "A" },
    { resi: 76, resn: "E", chain: "A" },
    { resi: 77, resn: "N", chain: "A" },
    { resi: 78, resn: "A", chain: "A" },
    { resi: 79, resn: "L", chain: "A" },
    { resi: 80, resn: "S", chain: "A" },
    { resi: 81, resn: "L", chain: "A" },
    { resi: 82, resn: "L", chain: "A" },
    { resi: 83, resn: "D", chain: "A" },
    { resi: 84, resn: "K", chain: "A" },
    { resi: 85, resn: "I", chain: "A" },
    { resi: 86, resn: "Y", chain: "A" },
    { resi: 87, resn: "T", chain: "A" },
    { resi: 88, resn: "S", chain: "A" },
    { resi: 89, resn: "P", chain: "A" },
    { resi: 90, resn: "L", chain: "A" },
    { resi: 91, resn: "C", chain: "A" },
  ],
  variants: [
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [5],
        residues: [{ resi: 5, resn: "Arg", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [18],
        residues: [{ resi: 18, resn: "Trp", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [37],
        residues: [{ resi: 37, resn: "Thr", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [42],
        residues: [{ resi: 42, resn: "Glu", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [51],
        residues: [{ resi: 51, resn: "Lys", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [53],
        residues: [{ resi: 53, resn: "Leu", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [58],
        residues: [{ resi: 58, resn: "Glu", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [62],
        residues: [{ resi: 62, resn: "Ile", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [82],
        residues: [{ resi: 82, resn: "Leu", chain: "A" }],
      },
    },
    {
      variant_type: "domestic",
      stats: [
        "SNP: $/$",
        "X% of cats (50 total)",
        "X cats with substitution",
        "X cats with ambiguity",
      ],
      region: {
        indices: [89],
        residues: [{ resi: 89, resn: "Ser", chain: "A" }],
      },
    },
  ],
  conservedRegions: [],
};
