import { Sequence } from "./components/SequenceViz";
export const chain1_sequence: Sequence = {
    residues: [
        { resi: 0, resn: "M", chain: "A" },
        { resi: 1, resn: "K", chain: "A" },
        { resi: 2, resn: "G", chain: "A" },
        { resi: 3, resn: "A", chain: "A" },
        { resi: 4, resn: "R", chain: "A" },
        { resi: 5, resn: "V", chain: "A" },
        { resi: 6, resn: "L", chain: "A" },
        { resi: 7, resn: "V", chain: "A" },
        { resi: 8, resn: "L", chain: "A" },
        { resi: 9, resn: "L", chain: "A" },
        { resi: 10, resn: "W", chain: "A" },
        { resi: 11, resn: "A", chain: "A" },
        { resi: 12, resn: "A", chain: "A" },
        { resi: 13, resn: "L", chain: "A" },
        { resi: 14, resn: "L", chain: "A" },
        { resi: 15, resn: "L", chain: "A" },
        { resi: 16, resn: "I", chain: "A" },
        { resi: 17, resn: "W", chain: "A" },
        { resi: 18, resn: "G", chain: "A" },
        { resi: 19, resn: "G", chain: "A" },
        { resi: 20, resn: "N", chain: "A" },
        { resi: 21, resn: "C", chain: "A" },
        { resi: 22, resn: "E", chain: "A", structureIndex: 1 },
        { resi: 23, resn: "I", chain: "A", structureIndex: 2 },
        { resi: 24, resn: "C", chain: "A", structureIndex: 3 },
        { resi: 25, resn: "P", chain: "A", structureIndex: 4 },
        { resi: 26, resn: "A", chain: "A", structureIndex: 5 },
        { resi: 27, resn: "V", chain: "A", structureIndex: 6 },
        { resi: 28, resn: "K", chain: "A", structureIndex: 7 },
        { resi: 29, resn: "R", chain: "A", structureIndex: 8 },
        { resi: 30, resn: "D", chain: "A", structureIndex: 9 },
        { resi: 31, resn: "V", chain: "A", structureIndex: 10 },
        { resi: 32, resn: "D", chain: "A", structureIndex: 11 },
        { resi: 33, resn: "L", chain: "A", structureIndex: 12 },
        { resi: 34, resn: "F", chain: "A", structureIndex: 13 },
        { resi: 35, resn: "L", chain: "A", structureIndex: 14 },
        { resi: 36, resn: "T", chain: "A", structureIndex: 15 },
        { resi: 37, resn: "G", chain: "A", structureIndex: 16 },
        { resi: 38, resn: "T", chain: "A", structureIndex: 17 },
        { resi: 39, resn: "P", chain: "A", structureIndex: 18 },
        { resi: 40, resn: "D", chain: "A", structureIndex: 19 },
        { resi: 41, resn: "E", chain: "A", structureIndex: 20 },
        { resi: 42, resn: "Y", chain: "A", structureIndex: 21 },
        { resi: 43, resn: "V", chain: "A", structureIndex: 22 },
        { resi: 44, resn: "E", chain: "A", structureIndex: 23 },
        { resi: 45, resn: "Q", chain: "A", structureIndex: 24 },
        { resi: 46, resn: "V", chain: "A", structureIndex: 25 },
        { resi: 47, resn: "A", chain: "A", structureIndex: 26 },
        { resi: 48, resn: "Q", chain: "A", structureIndex: 27 },
        { resi: 49, resn: "Y", chain: "A", structureIndex: 28 },
        { resi: 50, resn: "K", chain: "A", structureIndex: 29 },
        { resi: 51, resn: "A", chain: "A", structureIndex: 30 },
        { resi: 52, resn: "L", chain: "A", structureIndex: 31 },
        { resi: 53, resn: "P", chain: "A", structureIndex: 32 },
        { resi: 54, resn: "V", chain: "A", structureIndex: 33 },
        { resi: 55, resn: "V", chain: "A", structureIndex: 34 },
        { resi: 56, resn: "L", chain: "A", structureIndex: 35 },
        { resi: 57, resn: "E", chain: "A", structureIndex: 36 },
        { resi: 58, resn: "N", chain: "A", structureIndex: 37 },
        { resi: 59, resn: "A", chain: "A", structureIndex: 38 },
        { resi: 60, resn: "R", chain: "A", structureIndex: 39 },
        { resi: 61, resn: "I", chain: "A", structureIndex: 40 },
        { resi: 62, resn: "L", chain: "A", structureIndex: 41 },
        { resi: 63, resn: "K", chain: "A", structureIndex: 42 },
        { resi: 64, resn: "N", chain: "A", structureIndex: 43 },
        { resi: 65, resn: "C", chain: "A", structureIndex: 44 },
        { resi: 66, resn: "V", chain: "A", structureIndex: 45 },
        { resi: 67, resn: "D", chain: "A", structureIndex: 46 },
        { resi: 68, resn: "A", chain: "A", structureIndex: 47 },
        { resi: 69, resn: "K", chain: "A", structureIndex: 48 },
        { resi: 70, resn: "M", chain: "A", structureIndex: 49 },
        { resi: 71, resn: "T", chain: "A", structureIndex: 50 },
        { resi: 72, resn: "E", chain: "A", structureIndex: 51 },
        { resi: 73, resn: "E", chain: "A", structureIndex: 52 },
        { resi: 74, resn: "D", chain: "A", structureIndex: 53 },
        { resi: 75, resn: "K", chain: "A", structureIndex: 54 },
        { resi: 76, resn: "E", chain: "A", structureIndex: 55 },
        { resi: 77, resn: "N", chain: "A", structureIndex: 56 },
        { resi: 78, resn: "A", chain: "A", structureIndex: 57 },
        { resi: 79, resn: "L", chain: "A", structureIndex: 58 },
        { resi: 80, resn: "S", chain: "A", structureIndex: 59 },
        { resi: 81, resn: "L", chain: "A", structureIndex: 60 },
        { resi: 82, resn: "L", chain: "A", structureIndex: 61 },
        { resi: 83, resn: "D", chain: "A", structureIndex: 62 },
        { resi: 84, resn: "K", chain: "A", structureIndex: 63 },
        { resi: 85, resn: "I", chain: "A", structureIndex: 64 },
        { resi: 86, resn: "Y", chain: "A", structureIndex: 65 },
        { resi: 87, resn: "T", chain: "A", structureIndex: 66 },
        { resi: 88, resn: "S", chain: "A", structureIndex: 67 },
        { resi: 89, resn: "P", chain: "A", structureIndex: 68 },
        { resi: 90, resn: "L", chain: "A", structureIndex: 69 },
        { resi: 91, resn: "C", chain: "A", structureIndex: 70 },
    ],
    variants: [
        {
            chain: "A",
            color: "#00b050",
            correlated_ids: [1, 4, 8],
            id: 0,
            indices: [4],
            stats: ["R → C", "20% of domestic cats"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#00b050",
            correlated_ids: [0, 4, 8],
            id: 1,
            indices: [17],
            stats: ["W → S", "24% of domestic cats"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#000000",
            correlated_ids: [3, 5, 6, 7, 9],
            id: 2,
            indices: [36],
            stats: ["T → M", "2% of domestic cats (one individual)"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#000000",
            correlated_ids: [2, 5, 6, 7, 9],
            id: 3,
            indices: [41],
            stats: ["E → K", "2% of domestic cats (one individual)"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#00b050",
            correlated_ids: [0, 1, 8],
            id: 4,
            indices: [50],
            stats: ["K → N", "28% of domestic cats"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#000000",
            correlated_ids: [2, 3, 6, 7, 9],
            id: 5,
            indices: [52],
            stats: ["L → R", "2% of domestic cats (one individual)"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#000000",
            correlated_ids: [2, 3, 5, 7, 9],
            id: 6,
            indices: [57],
            stats: ["E → A", "2% of domestic cats (one individual)"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#000000",
            correlated_ids: [2, 3, 5, 6, 9],
            id: 7,
            indices: [61],
            stats: ["I → N", "2% of domestic cats (one individual)"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#00b050",
            correlated_ids: [0, 1, 4],
            id: 8,
            indices: [81],
            stats: ["L → V", "26% of domestic cats"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#000000",
            correlated_ids: [2, 3, 5, 6, 7],
            id: 9,
            indices: [88],
            stats: ["S → N", "2% of domestic cats (one individual)"],
            variant_type: "domestic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [13, 14, 16, 18, 19, 22, 23, 25, 26],
            id: 10,
            indices: [1],
            stats: ["K → E", "12.5% of exotic cats analyzed", "Species: Cougar"],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#7030a0",
            correlated_ids: [12, 15, 17, 20, 21, 24],
            id: 11,
            indices: [4],
            stats: [
                "R → C or H",
                "(C) 25% of exotic cats analyzed\n",
                "(H) 12.5% of exotic cats analyzed",
                "Species: (C) Leopard cat, fishing cat\n(H) Iberian lynx",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#7030a0",
            correlated_ids: [11, 15, 17, 20, 21, 24],
            id: 12,
            indices: [17],
            stats: [
                "W → S",
                "100% of exotic cats analyzed",
                "Species: Cougar, black-footed cat, Chinese mountain cat, Iberian ",
                "lynx, African lion, Bengal tiger, leopard cat, fishing cat",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 14, 16, 18, 19, 22, 23, 25, 26],
            id: 13,
            indices: [25],
            stats: [
                "P → S",
                "50% of exotic cats analyzed",
                "Species: Cougar, Iberian lynx, African lion, Bengal tiger",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 13, 16, 18, 19, 22, 23, 25, 26],
            id: 14,
            indices: [30],
            stats: [
                "D → I/N",
                "12.5% of exotic cats analyzed (I)\n",
                "12.5% of exotic cats analyzed (N)",
                "Species: African lion(I)\nBengal tiger (N)",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#7030a0",
            correlated_ids: [11, 12, 17, 20, 21, 24],
            id: 15,
            indices: [50],
            stats: [
                "K → N/S",
                "87.5% of exotic cats analyzed (K)\n",
                "12.5% of exotic cats analyzed (S)",
                "Species: Cougar, Chinese mountain cat, Iberian lynx, African ",
                "lion, Bengal tiger, leopard cat, fishing cat (K)\n",
                "Black-footed cat (S)",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 13, 14, 18, 19, 22, 23, 25, 26],
            id: 16,
            indices: [51],
            stats: [
                "A → T",
                "25% of exotic cats analyzed",
                "Species: Leopard cat, fishing cat",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#7030a0",
            correlated_ids: [11, 12, 15, 20, 21, 24],
            id: 17,
            indices: [52],
            stats: [
                "L → R/S/E",
                "37.5% of exotic cats analyzed (R)\n",
                "12.5% of exotic cats analyzed (S)\n",
                "25% of exotic cats analyzed (E)",
                "Species: Cougar, African lion, Bengal tiger (R)\n",
                "Iberian lynx (S)\n",
                "Leopard cat, fishing cat (E)",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 13, 14, 16, 19, 22, 23, 25, 26],
            id: 18,
            indices: [53],
            stats: [
                "P → S",
                "62.5% of exotic cats analyzed",
                "Species: Black-footed cat, African lion, Bengal tiger, leopard ",
                "cat, fishing cat",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 13, 14, 16, 18, 22, 23, 25, 26],
            id: 19,
            indices: [54],
            stats: [
                "V → E",
                "25% of exotic cats analyzed",
                "Species: Leopard cat, fishing cat",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#7030a0",
            correlated_ids: [11, 12, 15, 17, 21, 24],
            id: 20,
            indices: [57],
            stats: [
                "E → A/D/K",
                "25% of exotic cats analyzed (A)\n",
                "25% of exotic cats analyzed (D)\n",
                "8.3% of exotic cats analyzed (K)",
                "Species: Cougar, Iberian lynx (A)\n",
                "African lion, Bengal tiger (D)\n",
                "Leopard cat (K)",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#7030a0",
            correlated_ids: [11, 12, 15, 17, 20, 24],
            id: 21,
            indices: [61],
            stats: [
                "I → N/K/T",
                "12.5% of exotic cats analyzed (N)\n",
                "25% of exotic cats analyzed (K)\n",
                "25% of exotic cats analyzed (T)",
                "Species: Black-footed cat (N)\n",
                "Cougar, Iberian lynx (K)\n",
                "African lion, Bengal tiger (T)",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 13, 14, 16, 18, 19, 23, 25, 26],
            id: 22,
            indices: [66],
            stats: [
                "V → I/A",
                "8.3% of exotic cats analyzed (I)\n",
                "12.5% of exotic cats analyzed (A)",
                "Species: Cougar (I)\nAfrican lion (A)",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 13, 14, 16, 18, 19, 22, 25, 26],
            id: 23,
            indices: [75],
            stats: [
                "K → T",
                "12.5% of exotic cats analyzed",
                "Species: Black-footed cat",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#7030a0",
            correlated_ids: [11, 12, 15, 17, 20, 21],
            id: 24,
            indices: [81],
            stats: [
                "L → V",
                "50% of exotic cats analyzed",
                "Species: Cougar, Iberian lynx, African lion, Bengal tiger",
            ],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 13, 14, 16, 18, 19, 22, 23, 26],
            id: 25,
            indices: [84],
            stats: ["K → R", "8.3% of exotic cats analyzed", "Species: Leopard cat"],
            variant_type: "exotic",
        },
        {
            chain: "A",
            color: "#d60093",
            correlated_ids: [10, 13, 14, 16, 18, 19, 22, 23, 25],
            id: 26,
            indices: [90],
            stats: [
                "L → G",
                "25% of exotic cats analyzed",
                "Species: Cougar, Iberian lynx",
            ],
            variant_type: "exotic",
        },
    ],
    conservedRegions: [],
};
